language: ruby
rvm:
- 2.4.1
script:
- bundle exec rspec
deploy:
  provider: heroku
  app: gut-savvy-service
  api_key:
    secure: jthysm49VlBL3WIFRH7Q4dieO+07emP4q2bilmh9JK+QzSzvsBKw+7siffRp/wQXm0keKAuWjBMirD4JeD0rYpwzRjaRZr4E/06RheBV7HpomHK1FyofXxzQ8jXoZBENHcmwylhSf288pQ7TLxiU02kxvsa8VdvvvKD5TN2+KwvX4P9s6L9+JdUXFHpppmtJ8rsMqccMZc3sicWpfcHgdVfT3egB5H8GdFaJXh2V6foxU7i+yhO4rReqbafIon7Y8twpD+UwyETm12LFw9rRclHXZ2Cm0LZwi3Qg2xsFHcHpjMuqd1v0FzMZWfOWJ5rRWrBrwOFbxyBpR/4LQztf9CoseIr6xBGjrVvMc089wMHDu/07xxxuSUoIf6OR3Aw17PtH0DMzHcougUv/2C5M+gpL0eE2+nnJ1TbK16bX6F0QsErkJ8TsvZERqHz2YmSMCuQopDVQ1O4QL0oJHi9fvCeIPsQSlN+IvLaysmhUwjTa9MX/dLJXO2TvTAcI3M4FEn13DifOkBbRXHXleSE2nD49igaVEtsucoH4iOccy+QDZ4xQHO/EkzfkXFiTu1IylskY1de/c9JUyOqITMmEt8nuem0dUDCgGuV5JH8+YWMaKmA0lMVSOGtzQUXg6VOqd5JbqKGqmW6PyiJSYxLFqy+62LSCAjMptKA8O0fCLsc=
