language: ruby
rvm:
- 2.4.1
deploy:
  provider: heroku
  app: gut-savvy-service
  api_key:
    secure: CP2Z0YIoHBUAzCd8rR2Lqa79LKrv41y2bGTsO0j4fJUrB/yR555RKfeZJVGtKkJNEJRd2xhdE9X62ra9eZwnaSgJo3OJg/7r7FmwtG8+2xZntOJZLfp2nOO9DmEeLe29Vp/qOz1S9YOWYI6cRq86kxZ8UuwE+7Uncy+1OoY+mCPIBaTdNCzzaFkU9NpGxql86FVxxNBisIAQXIMfHLIGojGD/RHOTQVQEZEYQfVdpEu45KLCVuiC1y0JAwYuS4RxDt+8AuM68e6Pc8rrouLlY0xqhMOJg10L2F0AfYeWZpaTEAPyajvyr9kwVhf47kS+y31aLLzz2qmfb0u6Ux/tLaXn0JukUB/5gA6/OkGryFsOPmptxBOcehIRyp3STywAZg30BJz2kfHhLRc3erKvWLm++VFvIZW4DKss5+IFcplPDPcZHAc2FromE5Ei8cBq3jPB1ZMb4GzAe0M2AO78SLscQM5yGDDErkzs6M8DgSsuekCGM6apzw1xLKASbX71iY6LODvBu/dNMRDVHnbGKlIOXqhw7yZg8hO7exVrZNAWuDzp/O42cthFdzDKpRaM8Zt8JnZ1VoFVaHsstS2bcyc428f37aUph0bZfs9DjAtS/GV++G8j3Z4nefv/uZFLFaBxsk/+l1945DKPJ15ZMit5kJQj4R5pBmOl8NTYE7U=
